apiVersion: v2
appVersion: 0.0.1
name: aws-nth-crossplane-resources
description: Please add description
home: https://github.com/giantswarm/aws-nth-crossplane-resources
icon: https://s.giantswarm.io/app-icons/aws/2/light.svg
sources:
  - https://github.com/giantswarm/aws-nth-crossplane-resources
version: 1.0.0
annotations:
  application.giantswarm.io/team: phoenix
